import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Fridge Stalker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-slate-50 text-slate-900 antialiased">
        <div className="flex min-h-screen flex-col">
          <div className="flex-1">{children}</div>

          <footer className="border-t border-slate-200 bg-white/90 backdrop-blur-sm">
            <div className="mx-auto flex max-w-7xl items-center justify-center gap-2 px-4 py-4 text-sm text-slate-600">
              <span className="font-semibold text-slate-800">Built by Eazybel</span>
              <span aria-hidden="true">•</span>
              <span>Fridge Stalker</span>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
