import type { Metadata } from "next";
import Header from "@/app/components/Header/Header"
import "./globals.css";

export const metadata: Metadata = {
  title: "Fridge Stalker",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        <Header/>
        {children}
        </body>
    </html>
  );
}
